version: '3'

services:
  pgdb:
    #image: postgres
    image: postgres:13.0-alpine
    container_name: pgdbfab
    environment:
      - POSTGRES_DB=dbfab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
      #volumes:
      #- pgdata:/var/lib/postgresql/data/

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - pgdb
  web:
    build: .
    #command:
    #- python manage.py runserver 0.0.0.0:8000
    #command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "cd /usr/src/app/ &&
             python manage.py migrate &&             
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - pgdb

volumes:
  postgres_data: