# Generated by Django 4.1.2 on 2022-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=79999999999, max_length=11)),
                ('operator_code', models.IntegerField(default=919)),
                ('tag', models.CharField(default='tag', max_length=20)),
                ('time_zone', models.CharField(default='UTC', max_length=10)),
            ],
        ),
    ]
