# Generated by Django 4.1.2 on 2022-10-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mailingmodel_messagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='mailing_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mailingmodel'),
        ),
    ]
