# Generated by Django 4.1.2 on 2022-10-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_messagemodel_mailing_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='child_mailing',
        ),
    ]
