# Generated by Django 4.1.2 on 2022-10-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_messagemodel_child_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='mailing_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mailing', to='api.mailingmodel'),
        ),
    ]
