# Generated by Django 4.1.2 on 2022-10-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_clientmodel_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='status',
            field=models.CharField(default='Отправлено', max_length=50),
        ),
    ]
